server:
  port: 10001

#test
spring:
  data:
    maria:
      jdbc-url: #jdbc:mariadb://endpoint:3306/dbname?useUnicode=yes&characterEncoding=UTF-8
      driver-class-name: org.mariadb.jdbc.Driver
      username: #admin
      password: #1234!
  jpa:
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
    generate-ddl: true